import { useState } from 'react';
import RiskGauge from '../RiskGauge/RiskGauge';
import ClauseCard from '../ClauseCard/ClauseCard';
import {
  FileText, AlertTriangle, HelpCircle, ArrowLeft,
  ChevronDown, ChevronUp, Download, FileJson, Copy, Check,
  PieChart
} from 'lucide-react';
import './Dashboard.css';

/**
 * Generates a plain-text report from the analysis for PDF-style export.
 */
function generateTextReport(analysis, sortedClauses, allQuestions) {
  const lines = [];
  lines.push('═══════════════════════════════════════════════════');
  lines.push('           AEGIS CONTRACT RISK ANALYSIS REPORT');
  lines.push('═══════════════════════════════════════════════════');
  lines.push('');
  lines.push(`Document: ${analysis.originalFileName || 'Unknown'}`);
  lines.push(`Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push(`Overall Risk Score: ${analysis.overall_risk_score || 0} / 100`);
  lines.push(`Risk Profile: ${analysis.risk_profile || 'N/A'}`);
  lines.push('');
  lines.push('── EXECUTIVE SUMMARY ──────────────────────────────');
  lines.push(analysis.summary || '');
  lines.push('');

  if (sortedClauses.length > 0) {
    lines.push('── FLAGGED CLAUSES ───────────────────────────────');
    lines.push('');

    sortedClauses.forEach((clause, idx) => {
      lines.push(`┌─ Clause ${idx + 1}: ${(clause.risk_category || 'unknown').replace(/_/g, ' ').toUpperCase()}`);
      lines.push(`│  Risk Score: ${clause.risk_score}/100  |  Confidence: ${((clause.confidence || 0) * 100).toFixed(0)}%`);
      lines.push(`│`);
      lines.push(`│  Original Text:`);
      lines.push(`│  "${clause.original_text}"`);
      lines.push(`│`);
      lines.push(`│  🛡️ User Advocate: ${clause.advocate_argument}`);
      lines.push(`│  ⚖️ Strict Judge: ${clause.judge_argument}`);
      lines.push(`│  👥 Opposing Counsel: ${clause.counsel_argument}`);

      if (clause.scenario) {
        lines.push(`│`);
        lines.push(`│  ⚠️ Scenario: ${clause.scenario}`);
      }

      if (clause.questions?.self_directed?.length > 0) {
        lines.push(`│`);
        lines.push(`│  Questions to ask yourself:`);
        clause.questions.self_directed.forEach((q) => lines.push(`│    • ${q}`));
      }
      if (clause.questions?.counterparty?.length > 0) {
        lines.push(`│  Questions for the other party:`);
        clause.questions.counterparty.forEach((q) => lines.push(`│    • ${q}`));
      }
      lines.push(`└─────────────────────────────────────────────────`);
      lines.push('');
    });
  }

  lines.push('── DISCLAIMER ────────────────────────────────────');
  lines.push(analysis.disclaimer || 'AEGIS provides informational insights only and does not constitute legal advice. Consult a qualified attorney for legal decisions.');
  lines.push('');
  lines.push('Generated by AEGIS — Adaptive Evolving Guardian for Intelligent Synthesis');
  return lines.join('\n');
}

export default function Dashboard({ analysis, analysisId, onBack }) {
  const [showAllQuestions, setShowAllQuestions] = useState(false);
  const [showCategories, setShowCategories] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!analysis) return null;

  const sortedClauses = [...(analysis.clauses || [])].sort(
    (a, b) => (b.risk_score || 0) - (a.risk_score || 0)
  );

  const criticalCount = sortedClauses.filter((c) => c.risk_score > 75).length;
  const highCount = sortedClauses.filter((c) => c.risk_score > 50 && c.risk_score <= 75).length;

  // Collect ALL questions from all clauses with severity
  const allQuestions = sortedClauses.flatMap((c) => {
    const severity = c.risk_score > 75 ? 'Critical' : c.risk_score > 50 ? 'Important' : 'Nice-to-know';
    const selfQ = (c.questions?.self_directed || []).map((q) => ({
      text: q,
      type: 'self',
      category: c.risk_category,
      clauseId: c.clause_id,
      severity,
      riskScore: c.risk_score,
    }));
    const counterQ = (c.questions?.counterparty || []).map((q) => ({
      text: q,
      type: 'counter',
      category: c.risk_category,
      clauseId: c.clause_id,
      severity,
      riskScore: c.risk_score,
    }));
    return [...selfQ, ...counterQ];
  });

  const totalQuestions = allQuestions.length;

  // Category breakdown
  const categoryMap = {};
  sortedClauses.forEach((c) => {
    const cat = c.risk_category || 'other';
    if (!categoryMap[cat]) {
      categoryMap[cat] = { count: 0, totalScore: 0, maxScore: 0 };
    }
    categoryMap[cat].count++;
    categoryMap[cat].totalScore += c.risk_score || 0;
    categoryMap[cat].maxScore = Math.max(categoryMap[cat].maxScore, c.risk_score || 0);
  });
  const categories = Object.entries(categoryMap)
    .map(([name, data]) => ({
      name,
      label: name.replace(/_/g, ' '),
      count: data.count,
      avgScore: Math.round(data.totalScore / data.count),
      maxScore: data.maxScore,
    }))
    .sort((a, b) => b.maxScore - a.maxScore);

  // Average confidence
  const avgConfidence = sortedClauses.length > 0
    ? sortedClauses.reduce((s, c) => s + (c.confidence || 0), 0) / sortedClauses.length
    : 0;

  // Export handlers
  const handleExportJSON = () => {
    const blob = new Blob([JSON.stringify(analysis, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aegis-report-${analysisId || 'export'}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportText = () => {
    const report = generateTextReport(analysis, sortedClauses, allQuestions);
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aegis-report-${analysisId || 'export'}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyReport = async () => {
    const report = generateTextReport(analysis, sortedClauses, allQuestions);
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const ta = document.createElement('textarea');
      ta.value = report;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const getSeverityClass = (severity) => {
    switch (severity) {
      case 'Critical': return 'severity-critical';
      case 'Important': return 'severity-important';
      default: return 'severity-low';
    }
  };

  const getCategoryColor = (maxScore) => {
    if (maxScore > 75) return 'var(--risk-critical)';
    if (maxScore > 50) return 'var(--risk-high)';
    if (maxScore > 25) return 'var(--risk-moderate)';
    return 'var(--risk-low)';
  };

  return (
    <div className="dashboard animate-fade-in-up">
      {/* Top bar */}
      <div className="dashboard__topbar">
        <button className="btn btn-ghost" onClick={onBack} id="btn-back">
          <ArrowLeft size={16} />
          New Analysis
        </button>
        <div className="dashboard__export-group">
          <button className="btn btn-secondary btn-sm" onClick={handleCopyReport} id="btn-copy-report">
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
          <button className="btn btn-secondary btn-sm" onClick={handleExportText} id="btn-export-txt">
            <Download size={14} />
            Export TXT
          </button>
          <button className="btn btn-secondary btn-sm" onClick={handleExportJSON} id="btn-export-json">
            <FileJson size={14} />
            Export JSON
          </button>
        </div>
      </div>

      {/* Hero section */}
      <div className="dashboard__hero glass-panel">
        <div className="dashboard__hero-left">
          <div className="dashboard__gauge-wrap">
            <RiskGauge
              score={analysis.overall_risk_score || 0}
              profile={analysis.risk_profile || 'Low'}
              size={180}
            />
          </div>
        </div>

        <div className="dashboard__hero-right">
          <h2 className="dashboard__title">
            Risk Analysis Complete
          </h2>
          <p className="dashboard__filename">
            <FileText size={14} />
            {analysis.originalFileName || 'Document'}
          </p>
          <p className="dashboard__summary">{analysis.summary}</p>

          <div className="dashboard__stats">
            <div className="dashboard__stat">
              <span className="dashboard__stat-value" style={{ color: 'var(--risk-critical)' }}>
                {criticalCount}
              </span>
              <span className="dashboard__stat-label">Critical</span>
            </div>
            <div className="dashboard__stat">
              <span className="dashboard__stat-value" style={{ color: 'var(--risk-high)' }}>
                {highCount}
              </span>
              <span className="dashboard__stat-label">High Risk</span>
            </div>
            <div className="dashboard__stat">
              <span className="dashboard__stat-value" style={{ color: 'var(--accent-cyan)' }}>
                {sortedClauses.length}
              </span>
              <span className="dashboard__stat-label">Flagged</span>
            </div>
            <div className="dashboard__stat">
              <span className="dashboard__stat-value" style={{ color: 'var(--accent-violet)' }}>
                {totalQuestions}
              </span>
              <span className="dashboard__stat-label">Questions</span>
            </div>
            <div className="dashboard__stat">
              <span className="dashboard__stat-value" style={{ color: 'var(--accent-cyan)' }}>
                {(avgConfidence * 100).toFixed(0)}%
              </span>
              <span className="dashboard__stat-label">Confidence</span>
            </div>
          </div>
        </div>
      </div>

      {/* Disclaimer */}
      {analysis.disclaimer && (
        <div className="dashboard__disclaimer">
          <AlertTriangle size={14} />
          {analysis.disclaimer}
        </div>
      )}

      {/* Category Breakdown */}
      {categories.length > 0 && (
        <div className="dashboard__categories glass-panel">
          <button
            className="dashboard__categories-header"
            onClick={() => setShowCategories(!showCategories)}
            id="btn-toggle-categories"
          >
            <div className="dashboard__questions-header-left">
              <PieChart size={18} />
              <h3 className="dashboard__questions-title">
                Risk by Category ({categories.length})
              </h3>
            </div>
            {showCategories ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
          </button>

          {showCategories && (
            <div className="dashboard__categories-body animate-fade-in">
              {categories.map((cat) => (
                <div key={cat.name} className="dashboard__category-row">
                  <div className="dashboard__category-info">
                    <span className="dashboard__category-name">{cat.label}</span>
                    <span className="dashboard__category-count">{cat.count} clause{cat.count > 1 ? 's' : ''}</span>
                  </div>
                  <div className="dashboard__category-bar-wrap">
                    <div
                      className="dashboard__category-bar"
                      style={{
                        width: `${cat.maxScore}%`,
                        backgroundColor: getCategoryColor(cat.maxScore),
                      }}
                    />
                  </div>
                  <span className="dashboard__category-score" style={{ color: getCategoryColor(cat.maxScore) }}>
                    {cat.maxScore}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Questions Summary — always visible */}
      {totalQuestions > 0 && (
        <div className="dashboard__questions-panel glass-panel">
          <button
            className="dashboard__questions-header"
            onClick={() => setShowAllQuestions(!showAllQuestions)}
            id="btn-toggle-questions"
          >
            <div className="dashboard__questions-header-left">
              <HelpCircle size={18} />
              <h3 className="dashboard__questions-title">
                All Questions ({totalQuestions})
              </h3>
            </div>
            {showAllQuestions ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
          </button>

          {showAllQuestions && (
            <div className="dashboard__questions-body animate-fade-in">
              {/* Self-directed questions */}
              {allQuestions.filter((q) => q.type === 'self').length > 0 && (
                <div className="dashboard__questions-group">
                  <span className="dashboard__questions-label dashboard__questions-label--self">
                    🤔 Ask Yourself
                  </span>
                  <ul className="dashboard__questions-list">
                    {allQuestions
                      .filter((q) => q.type === 'self')
                      .map((q, i) => (
                        <li key={`self-${i}`} className="dashboard__question-item">
                          <span className={`dashboard__question-severity ${getSeverityClass(q.severity)}`}>
                            {q.severity}
                          </span>
                          <span className="dashboard__question-cat">
                            {q.category?.replace(/_/g, ' ')}
                          </span>
                          {q.text}
                        </li>
                      ))}
                  </ul>
                </div>
              )}

              {/* Counterparty questions */}
              {allQuestions.filter((q) => q.type === 'counter').length > 0 && (
                <div className="dashboard__questions-group">
                  <span className="dashboard__questions-label dashboard__questions-label--counter">
                    🤝 Ask the Other Party
                  </span>
                  <ul className="dashboard__questions-list dashboard__questions-list--counter">
                    {allQuestions
                      .filter((q) => q.type === 'counter')
                      .map((q, i) => (
                        <li key={`counter-${i}`} className="dashboard__question-item">
                          <span className={`dashboard__question-severity ${getSeverityClass(q.severity)}`}>
                            {q.severity}
                          </span>
                          <span className="dashboard__question-cat">
                            {q.category?.replace(/_/g, ' ')}
                          </span>
                          {q.text}
                        </li>
                      ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Clauses */}
      <div className="dashboard__clauses">
        <h3 className="dashboard__clauses-title">
          <AlertTriangle size={18} />
          Flagged Clauses ({sortedClauses.length})
        </h3>
        <p className="dashboard__clauses-hint">
          Click each clause to expand and see the full AI debate, scenario analysis, and questions.
        </p>
        <div className="dashboard__clauses-list stagger-children">
          {sortedClauses.map((clause, idx) => (
            <ClauseCard
              key={clause.clause_id || idx}
              clause={clause}
              analysisId={analysisId}
              index={idx}
              defaultExpanded={idx === 0}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
